# Generated by Django 4.1 on 2022-08-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('nonce', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('prev_hash', models.CharField(max_length=100)),
                ('time_stamp', models.TimeField()),
            ],
        ),
    ]
