# Generated by Django 4.1 on 2022-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='mined',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
